import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter  } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar"; 

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "My Resume App",
  description: "Generated by Next.js 15",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}>
        <Navbar /> 
        <main>{children}</main>
      </body>
    </html>
  );
}
